# Generated by Django 2.1.3 on 2019-02-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmessage',
            name='author',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
    ]
