# Generated by Django 2.1.3 on 2019-02-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190227_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmessage',
            name='author',
            field=models.CharField(default='', max_length=20),
        ),
    ]
